---
# tasks file for sublime-text

- name: import os specific setup
  include_tasks: "setup_{{ ansible_os_family }}.yml"

# Install Package Control

- name: Check Package Control path
  stat: path="{{ sublime_package_control_package_path }}"
  register: package_control_package_path
  when: sublime_package_control

- name: Install package control for sublime
  get_url: 
    url="{{ sublime_package_control_url }}/Package%20Control.sublime-package"
    dest="{{ sublime_installed_packages_dir }}/Package Control.sublime-package"
  when: sublime_package_control and (package_control_package_path.stat.isfile is not defined)

# Install & Configure Sublime Text Packages

- name: Install all custom packages
  git:
    repo="{{ item.value }}"
    dest="{{ sublime_packages_dir }}/{{ item.key }}"
    accept_hostkey="yes"
  with_dict: "{{ sublime_packages }}"
  when: sublime_package_control